/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.o3.bitcoin.ui.dialogs;

import com.o3.bitcoin.model.manager.ConfigManager;
import com.o3.bitcoin.service.WalletService;
import com.o3.bitcoin.ui.component.XButtonFactory;
import com.o3.bitcoin.ui.dialogs.screens.PnlNewRequestPaymentScreen;
import com.o3.bitcoin.ui.screens.wallet.PnlWalletScreen;
import com.o3.bitcoin.util.ResourcesProvider;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JPanel;
import org.bitcoinj.core.Wallet;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.FileWriter;
import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import org.jdom2.Attribute;
import org.jdom2.Document;
import org.jdom2.Element;
import org.jdom2.JDOMException;
import org.jdom2.input.SAXBuilder;
import org.jdom2.output.Format;
import org.jdom2.output.XMLOutputter;

/**
 *
 * @author LPS-PC
 */
public class DlgRequestPayment extends BasicDialog {

    private static final Logger logger = LoggerFactory.getLogger(DlgRequestPayment.class);
    private final WalletService service;
    private PnlNewRequestPaymentScreen pnlNewRequestPaymentScreen;
    private JButton paymentButton;
    private List<JButton> controls = new ArrayList<>();
    public static boolean isClicked = false;
    String xmlFilePath  = "";

    /** 
     * Creates new form DlgRequestPayment
     *
     * @param service
     */
    public DlgRequestPayment(WalletService service) {
        super(false);
        this.service = service;
        setupUI();
    }
    
    

    @Override
    protected JPanel getMainContentPanel() {
        if (pnlNewRequestPaymentScreen == null) {
            pnlNewRequestPaymentScreen = new PnlNewRequestPaymentScreen(this);
        }
        return pnlNewRequestPaymentScreen;
    }

//    public void setReceiveAddress(String address) {
//        pnlNewRequestPaymentScreen.setReceiveAddress(address);
//    }
    public void setAmount(String amount) {
        pnlNewRequestPaymentScreen.setAmount(amount);
    }

    public void complete(Wallet.SendResult res) {

    }

    @Override
    protected List<JButton> getControls() {
        controls = super.getControls();
        return controls;
    }
    
    @Override
    protected String getHeadingText() {
        return "Payment Request";
    }

    @Override
    protected void handleCloseDialogControlEvent(ActionEvent e) {
        super.handleCloseDialogControlEvent(e);
    }

    @Override
    protected void handleDefaultCloseEvent(ActionEvent e) {
        handleCloseDialogControlEvent(e);
    }

    public void markPaymentPending(boolean paymentPending) {
        controls.get(0).setEnabled(!paymentPending);
    }

    public void markWatchOnly() {
        try {
            service.getWalletConfig().setWatchOnly(true);
            ConfigManager.get().save();
        } catch (Exception ex2) {
            logger.error("Save Watch-Only config [{}]: Unable to save config: ", service.getWalletConfig().getId(), ex2);
        }
        this.dispose();
    }

    public void disablePaymentButton() {
        paymentButton.setEnabled(false);
    }

    public void enablePaymentButton() {
        paymentButton.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    // Variables declaration - do not modify                     
    // End of variables declaration            
}
